In [1]:
#import pandas as pd
with open('test.txt', mode='wb+') as file:
    file.write(b'\xd1\xe5\xea\xf0\xe5\xf2\xed\xee\xe5 \xf1\xeb\xee\xe2\xee: \xef\xf3\xf5\xee\xe2\xe8\xf7\xee\xea')

In [2]:
import os
with open('test.txt', mode ='r', encoding = 'cp1251') as file:
    print(file.readlines())

['Секретное слово: пуховичок']

In [3]:
%pip install gspread-pandas

Collecting gspread-pandas
  Downloading gspread_pandas-2.3.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: decorator in /home/julia/anaconda3/lib/python3.8/site-packages (from gspread-pandas) (4.4.2)
Requirement already satisfied: google-auth in /home/julia/.local/lib/python3.8/site-packages (from gspread-pandas) (1.28.0)
Requirement already satisfied: six in /home/julia/anaconda3/lib/python3.8/site-packages (from gspread-pandas) (1.15.0)
Collecting gspread>=3.0.0
  Downloading gspread-3.7.0-py3-none-any.whl (28 kB)
Requirement already satisfied: pandas>=0.20.0 in /home/julia/anaconda3/lib/python3.8/site-packages (from gspread-pandas) (1.1.3)
Requirement already satisfied: google-auth-oauthlib in /home/julia/.local/lib/python3.8/site-packages (from gspread-pandas) (0.4.4)
Requirement already satisfied: setuptools>=40.3.0 in /home/julia/anaconda3/lib/python3.8/site-packages (from google-auth->gspread-pandas) (50.3.1.post20201107)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /home/julia/.local/lib/python3.8/site-packages (from google-auth->gspread-pandas) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/julia/.local/lib/python3.8/site-packages (from google-auth->gspread-pandas) (4.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/julia/.local/lib/python3.8/site-packages (from google-auth->gspread-pandas) (0.2.8)
Requirement already satisfied: numpy>=1.15.4 in /home/julia/anaconda3/lib/python3.8/site-packages (from pandas>=0.20.0->gspread-pandas) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in /home/julia/anaconda3/lib/python3.8/site-packages (from pandas>=0.20.0->gspread-pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/julia/anaconda3/lib/python3.8/site-packages (from pandas>=0.20.0->gspread-pandas) (2.8.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/julia/.local/lib/python3.8/site-packages (from google-auth-oauthlib->gspread-pandas) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/julia/.local/lib/python3.8/site-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth->gspread-pandas) (0.4.8)
Requirement already satisfied: requests>=2.0.0 in /home/julia/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (2.24.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/julia/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (3.1.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/julia/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/julia/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/julia/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/julia/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread-pandas) (1.25.11)
Installing collected packages: gspread, gspread-pandas
Successfully installed gspread-3.7.0 gspread-pandas-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import gspread_pandas

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('productstar_df.csv', index_col=0)

In [8]:
len(df)

474959

In [28]:
df

,shipped_at,order_id,item_total,order_state,store_id,retailer_id,promo_total,total_weight,completed_at,city_id,user_id,item_count
id,,,,,,,,,,,,
0,2018-05-20 01:42:14+00:00,557,3243.119268,complete,75,8,-200.0,6085,2018-05-19 09:16:54+00:00,1,9016,13
1,NaN,1097,4590.108329,canceled,62,8,0.0,3000,2017-01-25 05:06:43+00:00,1,9052,2
2,2017-06-14 03:26:44+00:00,3103,12018.548693,complete,62,8,0.0,179750,2017-06-12 03:52:36+00:00,1,9041,46
3,2017-06-12 00:16:40+00:00,3112,2467.022803,complete,62,8,0.0,9100,2017-06-11 01:01:29+00:00,1,9041,6
4,2017-05-31 05:23:53+00:00,3201,1461.915164,complete,68,15,0.0,5948,2017-05-30 22:59:38+00:00,1,9041,8
...,...,...,...,...,...,...,...,...,...,...,...,...
474954,2019-01-05 23:01:39+00:00,3642207,2261.725542,complete,63,8,0.0,39100,2019-01-05 11:07:53+00:00,1,67812,6
474955,NaN,3642208,3234.739393,canceled,75,8,0.0,12300,2018-12-16 22:49:59+00:00,1,144725,11
474956,2019-01-23 05:19:03+00:00,3642213,3621.669987,complete,75,8,0.0,48972,2019-01-22 11:44:37+00:00,1,22096,9
474957,2018-12-26 09:02:33+00:00,3642227,3089.668218,complete,73,8,0.0,25710,2018-12-26 04:38:16+00:00,1,9424,9
474958,2018-12-21 09:49:58+00:00,3642244,4110.140282,complete,136,16,0.0,30675,2018-12-21 06:27:28+00:00,1,131806,19

In [9]:
df['item_total'].sum() / df['item_count'].sum()

277.3234135925197